matrix:
    include:
        - name: "Plain tests"
          language: r
          cache: packages
          r: release
          before_install:
              - ./travis_install_deps.sh
              - R -e 'install.packages("BiocManager");BiocManager::install("MSnbase")'
          script: make test
        - name: "Planemo tests"
          dist: xenial # To get Python >=2.7.7
          language: python
          python:
              - "3.7"
          install:
              - pip install virtualenv
          script: make planemolint planemotest


notifications:
 email:
  recipients:
   - pierrick.roger@cea.fr
