matrix:
    include:
        - name: "Plain tests"
          language: r
          cache: packages
          r: release
          before_install:
              - R -e "devtools::install_version('batch', version = '1.1_5', repos = 'https://cloud.r-project.org/')"
              - R -e "devtools::install_version('igraph', version = '1.2.4.1', repos = 'https://cloud.r-project.org/')"
              - R -e "devtools::install_github('adelabriere/mineMS2', ref = 'v0.9.3')"
              - R -e 'install.packages("BiocManager");BiocManager::install("MSnbase")'
          script: make test
        - name: "Planemo tests"
          dist: xenial # To get Python >=2.7.7
          language: python
          python:
              - "3.7"
          install:
              - pip install virtualenv
          script: make planemolint planemotest


notifications:
 email:
  recipients:
   - pierrick.roger@cea.fr
